# Generated by Django 3.2.5 on 2022-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('NAME', models.CharField(max_length=20)),
                ('GUNAME', models.CharField(max_length=20)),
                ('NUMBER', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
