# Generated by Django 3.2.5 on 2022-11-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='curriculum',
            new_name='withu',
        ),
    ]
